<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EfLocalDb" />
    <PackageReference Include="MarkdownSnippets.MsBuild" PrivateAssets="all" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="ProjectDefaults" PrivateAssets="all" />
    <PackageReference Include="TUnit" />
    <PackageReference Include="Verify.EntityFramework" />
    <PackageReference Include="Verify.SqlServer" />
    <PackageReference Include="Verify.TUnit" />
    <PackageReference Include="Argon" />
    <PackageReference Include="DiffEngine" />
    <PackageReference Include="EmptyFiles" />
    <PackageReference Include="SimpleInfoName" />
    <PackageReference Include="Verify" />
    <ProjectReference Include="..\EfQueryComplexity\EfQueryComplexity.csproj" />
  </ItemGroup>

</Project>
